### PR TITLE
Added Building layer

### PR DESCRIPTION
**Pull request by gok03**
- Included Building layer
- Passed state from menu to map component for change listener

### CODE REVIEW

**Comment by RELNO** [comment]
@gok03 thanks! looks like `componentWillReceiveProps` is deprecated (see console) https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Also might worth pulling latest Master, since `picking` func is broken in your commit

**Comment by gok03** [comment]
Working on the same now.

**Comment by gok03** [comment]
Closing the PR to rebase the code.

**Comment by gok03** [comment]
> Also might worth pulling latest Master, since picking func is broken in your commit

master branch was latest in this PR. Can you give some info on picking func?

**Comment by RELNO** [comment]
Try pulling again, picking should be stable now. This is a selection method for multi cell editing. Also, last commit has crude layers control (based on what you’ve started doing), I’d appreciate your comments on that

**Pull request closed without merging**
