### PR TITLE
Roboscope Functionality

### PR DESCRIPTION
**Pull request by ayeshaali**
Added roboscope functionality (i.e. dynamic grid that can be scaled and translated and websocket communication with roboscope table)

- 3 new files: Websocket component, roboscope grid layer, roboscope selection layer (uses NebulaGL library)
- new toggles: scale (of selection layer) and translate (of selected features in grid layer), visible only if roboscope table

(For reference, future edits will include toggle for websockets, roboscope compatibility option in grid editor, UI elements such as an indicator that websockets are on, and some more work on websockets component)

### CODE REVIEW

**Comment by RELNO** [comment]
@ayeshaali thanks -- trying to compile, I'm getting a whole bunch of errors, can you look into these, as well as get `package,.json` from the master to align other libs? 
Screen Shot 2021-01-11 at 10 38 45 AM

**Comment by ayeshaali** [comment]
> @ayeshaali thanks -- trying to compile, I'm getting a whole bunch of errors, can you look into these, as well as get `package,.json` from the master to align other libs?
> Screen Shot 2021-01-11 at 10 38 45 AM

The new commit should take care of it once you install the libraries. Lmk if it's still giving you those errors.

**Comment by RELNO** [comment]
hi @ayeshaali -- just FYI, I'm in the middle of a pretty massive version coming up in the next few weeks. You can track some of the changes in https://github.com/CityScope/CS_cityscopeJS/tree/router. I suggest you consider how your work meet these changes. We can discuss offline as well.

**Comment by RELNO** [comment]
@ayeshaali is this PR still in development?

**Pull request closed without merging**
